prompts_file_path: 'prompts.json'
standard_deviations: [100, 200, 1000]
augmentation_types:
    noise_conv : true
    mask: false
save_path: '/workspace/aelif/results.json'
img_height: 768
img_width: 768
num_inference_steps: 28
guidance_scale: 7.0
seed: 0


