prompts_file_path: '/Users/borismartirosyan/Desktop/projects/aelif_augmentation/prompts.json'
standard_deviations: [0, 0.1, 1, 10, 100]
augmentation_types:
    noise_conv : true
    mask: false
save_path: '.'
img_height: 768
img_width: 768
num_inference_steps: 28
guidance_scale: 7.0
seed: 0